# -*- coding: utf-8 -*-
"""LicensePlate_Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orEaEtVgQk-vBNbCgzdiQYCV4eHl0T3X
"""

import os
HOME = os.getcwd()
print(HOME)

"""# Import Ultralytics and YOLO"""

!pip install ultralytics==8.2.103 -q

from IPython import display
display.clear_output()

!yolo settings sync=False

import ultralytics
ultralytics.checks()

"""#Import Annotated Dataset"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="0RnxDSy0zqP9tVYR5ZIy")
project = rf.workspace("test-1tja4").project("my-first-project2-lxjmd")
version = project.version(1)
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=train model=yolov8s.pt data={dataset.location}/data.yaml epochs=50 imgsz=800 plots=True

from IPython.display import Image, display
display(Image(filename='/content/runs/detect/train2/confusion_matrix.png',width=1000))

display(Image(filename='/content/runs/detect/train3/results.png',width=1000))

"""#Test Model"""

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=val model={HOME}/runs/detect/train3/weights/best.pt data={dataset.location}/data.yaml

import shutil

# Zip the folders into one file
shutil.make_archive("my_colab_folders", 'zip', root_dir=".", base_dir="My-First-Project2-1")
shutil.make_archive("runs_folder", 'zip', root_dir=".", base_dir="runs")

from google.colab import files

# Download the zipped folders
files.download("my_colab_folders.zip")
files.download("runs_folder.zip")

